/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ShopRouteImport } from './routes/_shop'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ShopIndexRouteImport } from './routes/_shop.index'
import { Route as AdminManageItemsRouteImport } from './routes/admin.manage-items'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminAddItemsRouteImport } from './routes/admin.add-items'
import { Route as ShopProductsRouteImport } from './routes/_shop.products'
import { Route as ShopOrderSuccessRouteImport } from './routes/_shop.order-success'
import { Route as ShopCheckoutRouteImport } from './routes/_shop.checkout'
import { Route as ShopCartRouteImport } from './routes/_shop.cart'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/_shop',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const AdminManageItemsRoute = AdminManageItemsRouteImport.update({
  id: '/manage-items',
  path: '/manage-items',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAddItemsRoute = AdminAddItemsRouteImport.update({
  id: '/add-items',
  path: '/add-items',
  getParentRoute: () => AdminRoute,
} as any)
const ShopProductsRoute = ShopProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => ShopRoute,
} as any)
const ShopOrderSuccessRoute = ShopOrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCheckoutRoute = ShopCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCartRoute = ShopCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => ShopRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShopIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof ShopCartRoute
  '/checkout': typeof ShopCheckoutRoute
  '/order-success': typeof ShopOrderSuccessRoute
  '/products': typeof ShopProductsRoute
  '/admin/add-items': typeof AdminAddItemsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/manage-items': typeof AdminManageItemsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/cart': typeof ShopCartRoute
  '/checkout': typeof ShopCheckoutRoute
  '/order-success': typeof ShopOrderSuccessRoute
  '/products': typeof ShopProductsRoute
  '/admin/add-items': typeof AdminAddItemsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/manage-items': typeof AdminManageItemsRoute
  '/': typeof ShopIndexRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shop': typeof ShopRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_shop/cart': typeof ShopCartRoute
  '/_shop/checkout': typeof ShopCheckoutRoute
  '/_shop/order-success': typeof ShopOrderSuccessRoute
  '/_shop/products': typeof ShopProductsRoute
  '/admin/add-items': typeof AdminAddItemsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/manage-items': typeof AdminManageItemsRoute
  '/_shop/': typeof ShopIndexRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/order-success'
    | '/products'
    | '/admin/add-items'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/manage-items'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/cart'
    | '/checkout'
    | '/order-success'
    | '/products'
    | '/admin/add-items'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/manage-items'
    | '/'
    | '/admin'
  id:
    | '__root__'
    | '/_shop'
    | '/admin'
    | '/_shop/cart'
    | '/_shop/checkout'
    | '/_shop/order-success'
    | '/_shop/products'
    | '/admin/add-items'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/manage-items'
    | '/_shop/'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShopRoute: typeof ShopRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shop': {
      id: '/_shop'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_shop/': {
      id: '/_shop/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/admin/manage-items': {
      id: '/admin/manage-items'
      path: '/manage-items'
      fullPath: '/admin/manage-items'
      preLoaderRoute: typeof AdminManageItemsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/add-items': {
      id: '/admin/add-items'
      path: '/add-items'
      fullPath: '/admin/add-items'
      preLoaderRoute: typeof AdminAddItemsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_shop/products': {
      id: '/_shop/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ShopProductsRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/order-success': {
      id: '/_shop/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof ShopOrderSuccessRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/checkout': {
      id: '/_shop/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof ShopCheckoutRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/cart': {
      id: '/_shop/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof ShopCartRouteImport
      parentRoute: typeof ShopRoute
    }
  }
}

interface ShopRouteChildren {
  ShopCartRoute: typeof ShopCartRoute
  ShopCheckoutRoute: typeof ShopCheckoutRoute
  ShopOrderSuccessRoute: typeof ShopOrderSuccessRoute
  ShopProductsRoute: typeof ShopProductsRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopCartRoute: ShopCartRoute,
  ShopCheckoutRoute: ShopCheckoutRoute,
  ShopOrderSuccessRoute: ShopOrderSuccessRoute,
  ShopProductsRoute: ShopProductsRoute,
  ShopIndexRoute: ShopIndexRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

interface AdminRouteChildren {
  AdminAddItemsRoute: typeof AdminAddItemsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminManageItemsRoute: typeof AdminManageItemsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAddItemsRoute: AdminAddItemsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminManageItemsRoute: AdminManageItemsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShopRoute: ShopRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
